name: CI AzurePipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Linter
        run: npm run lint

  integration-tests:
    runs-on: ubuntu-latest
    needs: [build, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Integration Tests
        run: npm run test:integration
