name: CI AzurePipeline

trigger:
  branches:
    include:
      - main
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'  # Máquina de entorno de ejecución
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'

      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: |
          echo Add other commands here
        displayName: 'Run multiple lines'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Integration Tests
        run: npm run test:integration
