# Nombre del pipeline
name: CI AzurePipeline

# Configuraci贸n de triggers
trigger:
  branches:
    include:
      - main  # Activa el pipeline en la rama main

pr:
  branches:
    include:
      - main  # Activa el pipeline en pull requests a la rama main

# Definici贸n de etapas y trabajos
jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: Checkout@1  # Comando para hacer checkout del c贸digo
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'  # Especifica la versi贸n de Node.js
    - script: npm install
      displayName: 'Install dependencies'
    - script: npm test
      displayName: 'Run Tests'

- job: Lint
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: Checkout@1
    - script: npm run lint
      displayName: 'Run Linter'

- job: IntegrationTests
  dependsOn:  # Especifica dependencias de otros trabajos
    - Build
    - Lint
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: Checkout@1
    - script: npm run test:integration
      displayName: 'Run Integration Tests'
